CREATE SET TABLE EIM_TDCOE.jenkins_test_automate11 ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      jenkins_ver VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      jenkins_user VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC,
      jenkins_pass VARCHAR(10) CHARACTER SET LATIN NOT CASESPECIFIC)
PRIMARY INDEX ( jenkins_ver );
